# Deployment spec for our Replicated Entity examples
apiVersion: cloudstate.io/v1alpha1
kind: StatefulService
metadata:
  name: replicated-entity-example
spec:
  containers:
    - image: akkaserverless/js-replicated-entity-example:latest
